create table if not exists public.demand_monitor_runs (
  id text primary key,
  started_at timestamptz not null,
  finished_at timestamptz,
  status text not null check (status in ('completed', 'failed')),
  queries_count integer not null default 0,
  results_count integer not null default 0,
  signals_count integer not null default 0,
  failures_count integer not null default 0,
  providers jsonb not null default '{}'::jsonb,
  failures jsonb not null default '[]'::jsonb,
  query_catalog jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.demand_signals (
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  last_run_id text references public.demand_monitor_runs(id) on delete set null,
  source text not null,
  category text not null,
  intent text not null,
  query text not null,
  title text not null,
  url text not null,
  snippet text not null default '',
  author text,
  published_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  score integer not null check (score between 0 and 100),
  score_reasons jsonb not null default '[]'::jsonb,
  emails jsonb not null default '[]'::jsonb,
  phones jsonb not null default '[]'::jsonb,
  social_urls jsonb not null default '[]'::jsonb,
  status text not null default 'new' check (status in ('new', 'qualified', 'dismissed')),
  created_at timestamptz not null default now()
);

create index if not exists demand_signals_review_idx
  on public.demand_signals (status, score desc, last_seen_at desc);
create index if not exists demand_signals_category_idx
  on public.demand_signals (category, last_seen_at desc);

alter table public.demand_monitor_runs enable row level security;
alter table public.demand_signals enable row level security;
revoke all on public.demand_monitor_runs from anon, authenticated;
revoke all on public.demand_signals from anon, authenticated;
