create table if not exists public.contact_search_runs (
  id text primary key,
  started_at timestamptz not null,
  finished_at timestamptz,
  mode text not null check (mode in ('dry-run', 'apply')),
  write_mode text not null check (write_mode in ('enrich', 'new_lead')),
  status text not null check (status in ('running', 'completed', 'failed')),
  companies_count integer not null default 0,
  candidates_count integer not null default 0,
  selected_count integer not null default 0,
  failures_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_search_companies (
  id bigint generated by default as identity primary key,
  run_id text not null references public.contact_search_runs(id) on delete cascade,
  source_lead_id bigint not null,
  company_name text not null,
  website text,
  warnings jsonb not null default '[]'::jsonb,
  duration_ms integer not null default 0,
  created_at timestamptz not null default now(),
  unique (run_id, source_lead_id)
);

create table if not exists public.contact_search_candidates (
  id bigint generated by default as identity primary key,
  run_id text not null references public.contact_search_runs(id) on delete cascade,
  company_id bigint not null references public.contact_search_companies(id) on delete cascade,
  source_lead_id bigint not null,
  company_name text not null,
  full_name text,
  position text,
  emails jsonb not null default '[]'::jsonb,
  phones jsonb not null default '[]'::jsonb,
  social_urls jsonb not null default '[]'::jsonb,
  evidence jsonb not null default '[]'::jsonb,
  score integer not null check (score between 0 and 100),
  score_reasons jsonb not null default '[]'::jsonb,
  decision text not null default 'pending' check (decision in ('pending', 'approved', 'rejected')),
  synced_at timestamptz,
  company_context jsonb not null,
  candidate_payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists contact_search_candidates_review_idx
  on public.contact_search_candidates (decision, synced_at, created_at desc);
create index if not exists contact_search_companies_run_idx
  on public.contact_search_companies (run_id);

alter table public.contact_search_runs enable row level security;
alter table public.contact_search_companies enable row level security;
alter table public.contact_search_candidates enable row level security;

revoke all on public.contact_search_runs from anon, authenticated;
revoke all on public.contact_search_companies from anon, authenticated;
revoke all on public.contact_search_candidates from anon, authenticated;

